# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11I9pBeIh9Ij5emedsyrrNZMqeLEisNT4

Name: Prathmesh Kulkarni

Importing Libraries
"""

import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import csv

"""Importing Dataset"""

data = pd.read_csv("/content/Unemployment in India.csv")
data = pd.read_csv("/content/Unemployment_Rate_upto_11_2020.csv")
print(data.head())

data.info

print(data.isnull().sum())

data.columns = ["States","Date","Frequency",
                "Estimated Unemployment Rate",
                "Estimated Employed",
                "Estimated Labour Participation Rate",
                "Region", "longitude","latitude"]

"""Correlation"""

plt.style.use('seaborn-whitegrid')
plt.figure(figsize=(12,10))
sns.heatmap(data.corr())
plt.show()

"""Data visualisation"""

data.columns = ["States","Date","Frequency",
                "Estimated Unemployment Rate",
                "Estimated Employed",
                "Estimated Labour Participation Rate",
                "Region", "longitude","latitude"]
plt.title("Indian Unemployment")
sns.histplot(x= "Estimated Employed",hue= "Region", data=data)
plt.show()

plt.figure(figsize=(12,10))
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Unemployment Rate", hue ="Region",data=data)
plt.show()

"""Analysing the Unemployment Rate for each Indian state."""

unemploment = data[["States", "Region", "Estimated Unemployment Rate"]]
figure = px.sunburst(unemploment,path=["Region","States"],
                    values= "Estimated Unemployment Rate",
                    width =700, height=700, color_continuous_scale="RdY1Gn",
                    title= "Unemployment Rate in India")
figure.show()

